wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_accuracy
      6:
      - 3
      7:
      - 2
    python_version: 3.10.4
    start_time: 1656590167
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.4
      5: 0.12.20
      6: 4.20.1
      8:
      - 1
      - 3
      - 5
adam_epsilon:
  desc: null
  value: 1.0e-08
data_dir:
  desc: null
  value: ''
dataset_name:
  desc: null
  value: RP-Mod
early_stop_callback:
  desc: null
  value: false
eval_batch_size:
  desc: null
  value: 8
fp_16:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0004
max_grad_norm:
  desc: null
  value: 0.5
max_seq_length:
  desc: null
  value: 512
model_name_or_path:
  desc: null
  value: GermanT5/t5-efficient-oscar-german-small-el32
n_gpu:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 20
opt_level:
  desc: null
  value: O1
output_dir:
  desc: null
  value: ./GermanT5-RP-Mod/t5-efficient-oscar-german-small-el32/
seed:
  desc: null
  value: 42
tokenizer_name_or_path:
  desc: null
  value: GermanT5/t5-efficient-oscar-german-small-el32
train_batch_size:
  desc: null
  value: 8
train_dataset:
  desc: null
  value: <__main__.RPDataset object at 0x000002724821D930>
val_dataset:
  desc: null
  value: <__main__.RPDataset object at 0x000002724821DF90>
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.1
